version: "3.8"

services:

  accounts:
    image: todddocker777/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - eaztbank-network
    
    
  loans:
    image: todddocker777/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - eaztbank-network
    
  cards:
    image: todddocker777/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - eaztbank-network
    
networks:
  eaztbank-network: