version: "3.8"

services:

  configserver:
    image: todddocker777/configserver:latest
    mem_limit: 700m
    ports: 
      - "8071:8071"
    networks:
      - eaztbank-network

  accounts:
    image: todddocker777/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - eaztbank-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
    
  loans:
    image: todddocker777/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - eaztbank-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
    
  cards:
    image: todddocker777/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - eaztbank-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
    
networks:
  eaztbank-network: