version: "3.8"

services:

  zipkin:
    image: openzipkin/zipkin
    mem_limit: 700m
    ports: 
      - "9411:9411"
    networks:
      - eaztbank-network

  configserver:
    image: todddocker777/configserver:latest
    mem_limit: 700m
    ports: 
      - "8071:8071"
    networks:
      - eaztbank-network
    depends_on:
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
      
  eurekaserver:
    image: todddocker777/eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - eaztbank-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 7
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  accounts:
    image: todddocker777/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - eaztbank-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 25s
        max_attempts: 5
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
    
  loans:
    image: todddocker777/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - eaztbank-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
    
  cards:
    image: todddocker777/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - eaztbank-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
    
  gatewayserver:
    image: todddocker777/gatewayserver:latest
    mem_limit: 700m
    ports: 
      - 8072:8072
    networks:
      - eaztbank-network
    depends_on:
      - configserver
      - eurekaserver
      - cards
      - loans
      - accounts
    deploy:
      restart_policy:
        condition: on-failure
        delay: 75s
        max_attempts: 7
        window: 280s
    environment: 
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
    
networks:
  eaztbank-network: